version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    working_directory: ~/my-project
    steps:
      - checkout
      - run:
          name: Update NPM
          command: &quot;sudo npm install -g npm&quot;
      - restore_cache:
          key: dependency-cache-{{ checksum &quot;package-lock.json&quot; }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum &quot;package-lock.json&quot; }}
          paths:
            - ./node_modules
      - run:
          name: Test React App
          command: npm run test
      - run:
          name: Build React App

Lab Guides Front-End Framework Issue/Revision: x/y

25e-BM/HR/HDCV/FSOFT v1.1 Internal use 9/4
          command: npm run build
workflows:
  build_and_deploy:
    jobs:
      - build