export const DATA_REQUEST = "DATA_REQUEST"
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_FAILURE = "DATA_FAILURE"

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const DATA_CART_REQUEST = "DATA_CART_REQUEST";
export const DATA_CART_SUCCESS = "DATA_CART_SUCCESS";
export const DATA_CART_FAILURE = "DATA_CART_FAILURE";

export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAILURE = "REMOVE_PRODUCT_FAILURE";

export const BOUGHT_PRODUCT_REQUEST = "BOUGHT_PRODUCT_REQUEST";
export const BOUGHT_PRODUCT_SUCCESS = "BOUGHT_PRODUCT_SUCCESS";
export const BOUGHT_PRODUCT_FAILURE = "BOUGHT_PRODUCT_FAILURE";

export const DATA_BOUGHT_REQUEST = "DATA_BOUGHT_REQUEST";
export const DATA_BOUGHT_SUCCESS = "DATA_BOUGHT_SUCCESS";
export const DATA_BOUGHT_FAILURE = "DATA_BOUGHT_FAILURE";

export const REMOVE_BOUGHT_REQUEST = "REMOVE_BOUGHT_REQUEST";
export const REMOVE_BOUGHT_SUCCESS = "REMOVE_BOUGHT_SUCCESS";
export const REMOVE_BOUGHT_FAILURE = "REMOVE_BOUGHT_FAILURE";

export const UPDATE_CART= "UPDATE_CART"
